name: github_issue_mover
description: Issue Mover for Github
homepage: https://github.com/google/github-issue-mover
dependencies:
  browser: any
  cookie: '>=0.0.4 <0.1.0'
  forcemvc: '>=0.7.1 <0.8.0'
  github: '>=2.1.3 <3.0.0'
  intl: any
  logging: '>=0.9.0 <0.10.0'
  markdown: '>=0.7.0 <0.8.0'
  yaml: '>=2.0.0 <3.0.0'
  appengine: any
